Get rid of Github Actions deprecations
symfony-cli/symfony-cli pull request #204
Opened 2022-10-28 14:07 UTC by NoResponseMate

2022-10-28 14:48 UTC, tucksaun requested changes

2022-11-03 20:51 UTC, tucksaun requested changes

2022-11-03 20:51 UTC, tucksaun commented on commands/local_check_security.go
> +	        if err = f.Close(); err != nil {
I would move both `f.Close()` calls just after opening the file and using `defer`

2022-11-03 20:51 UTC, tucksaun commented on commands/local_check_security.go
> +            f, err := os.OpenFile(gOutFile, os.O_APPEND|os.O_CREATE|os.O_WRONLY, 0644)
Golang community uses tabs for indentation, you can use `go fmt` to automatically format the file.

2022-11-13 16:32 UTC, kevinpapst commented
@NoResponseMate will that fix the deprecation warning `Warning: The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files.`, which is triggered when `symfony security:check` is run as part of a GitHub workflow?
<img width="979" alt="Bildschirmfoto 2022-11-13 um 17 30 47" src="https://user-images.githubusercontent.com/533162/201532776-ecef0eee-3585-47bb-8d38-aa982a1ffa9b.png">

2022-11-16 15:33 UTC, NoResponseMate commented
@kevinpapst Yeah, that's the goal

2022-11-18 09:44 UTC, merged

2022-11-18 09:44 UTC, fabpot commented
Thank you