feat(code-quality): add golangci-lint to CI and lint project
symfony-cli/symfony-cli pull request #245
Opened 2022-12-20 19:44 UTC by darkweak

Hello, this PR is here to have a better code quality/code style using `golangci-lint`. It adds the CI job to ensure every other PR will be as well written as possible.

2022-12-21 12:28 UTC, tucksaun requested changes
Thank you @darkweak for working on this 🙏
This has been on my mind for a while 👍

Just a couple of thoughts:

- I believe we should tweak the settings to match our use case though.
For example, `unusedresult` should probably be disabled (at least for several functions from `terminal`).

- We should also take the opportunity to some of those issues instead of masking them (not checking errors for example) which makes me believe it would be better to add the configuration in this PR, maybe fix the obvious issues (`ioutil`-> `os` for example) and fix the other issues with other PRs.
 
any thought @fabpot ?

2022-12-21 12:28 UTC, tucksaun commented on .github/workflows/go_generate_update.yml
> +                uses: golangci/golangci-lint-action@v3
we could enable `only-new-issues` in order to not overwhelm new contributors with code not up to date with quality

2022-12-21 13:09 UTC, darkweak commented on .github/workflows/go_generate_update.yml
> +                uses: golangci/golangci-lint-action@v3
You're right ✌️

2022-12-21 13:17 UTC, darkweak commented
> I believe we should tweak the settings to match our use case though.
For example, unusedresult should probably be disabled (at least for several functions from terminal).

IMHO if that's unused that should be removed 😄 

> We should also take the opportunity to some of those issues instead of masking them

That's the first iteration and was to implement asap the golangci-lint. I plan to add some error handling (for those I just disabled checks).

2022-12-21 19:12 UTC, darkweak commented on .github/workflows/go_generate_update.yml
> +                uses: golangci/golangci-lint-action@v3
After thinking about that, 
> we could enable only-new-issues in order to not overwhelm new contributors with code not up to date with quality

If they rebase their PR they'll have the correct code.

2023-01-13 23:34 UTC, tucksaun commented
> IMHO if that's unused that should be removed 😄

I'm not referring to unused but unused results that are not always useful and I personally find having tons of `_, _  = ` unreadable (see all the changes for functions as `terminal.Printfln`)

> That's the first iteration and was to implement asap the golangci-lint. I plan to add some error handling (for those I just disabled checks).

That is the reason why I mentioned enabling only-new-issues. By doing so we can more quickly merge this PR that would only add configuration and most obvious fix and then we can fix other issues in dedicated PRs

2023-01-14 11:13 UTC, darkweak commented
Oh sorry, I misunderstood what you said then, thank you for your explanations.
I'll try to find time to update the PR during this week-end 👍

2023-01-18 15:56 UTC, darkweak commented
@tucksaun the PR is ready.

2023-01-27 17:50 UTC, darkweak commented
@fabpot @tucksaun any update?

2023-02-01 16:41 UTC, tucksaun requested changes

2023-02-01 16:41 UTC, tucksaun commented on .golangci.yml
> +    - varcheck
we can remove `deadcode`, `varcheck` and `unused` from the list

2023-02-01 16:41 UTC, tucksaun commented on .golangci.yml
> +    - varcheck
also missing new line at the end of the file

2023-02-01 16:41 UTC, tucksaun commented on book/checkout.go
> +		return err
We usually wrap errors (with `errors.WithStack`) to get nice stack traces

2023-02-01 16:41 UTC, tucksaun commented on book/checkout.go
> +		return err
this also means `wrapcheck` should probably be enabled in golangci configuration

2023-02-01 16:41 UTC, tucksaun commented on .golangci.yml
> +    - varcheck
and regarding errcheck, given the fact that you fixed most of then we can enable errcheck and disable it only for terminal functions like `Println`

2023-02-01 16:41 UTC, tucksaun commented on .golangci.yml
> +    - varcheck
(see my other configuration suggestion)

2023-02-01 16:41 UTC, tucksaun commented on .golangci.yml
> +    - varcheck
```suggestion
linters:
  enable:
    - gci
    - wrapcheck

linters-settings:
  wrapcheck:
    ignorePackageGlobs:
      # We already make sure your own packages wrap errors properly
      - github.com/symfony-cli/*
  errcheck:
      ignore: github.com/symfony-cli/terminal:^(Ep|P)rint
```

2023-03-24 11:15 UTC, darkweak commented
Ping @tucksaun

2023-04-18 22:46 UTC, tucksaun requested changes
I'm stopping here because reviewing this kind of PR is complicated 😖.
Also, the PR needs rebasing.
Would you reconsider opening a new PR with only the configuration and then creating one PR per topic fixed (one by one)?
That would help a lot IMO as they are a couple of fixes that could be merged quickly then.

2023-04-18 22:46 UTC, tucksaun commented on .golangci.yml
> +      ignore: github.com/symfony-cli/terminal:^(Ep|P)rint
missing newline at the end of the file

2023-04-18 22:46 UTC, tucksaun commented on book/checkout.go
> +	}
```suggestion
	if err := errors.WithStack(os.Chdir(b.Dir)); err != nil {
		return err
	}
```

I'm not saying we have to do it, but we can do it when there's only a single return value, this also better preserve stack traces IIRC

2023-04-18 22:46 UTC, tucksaun commented on book/checkout.go
> -	executeCommand([]string{"symfony", "server:stop"}, b.Debug, true, nil)
I would tend to think that @fabpot deliberately skip this one

2023-04-18 22:46 UTC, tucksaun commented on book/checkout.go
> -		executeCommand([]string{"symfony", "server:stop", "--dir", filepath.Join(b.Dir, "spa")}, b.Debug, true, nil)
same

2023-04-18 22:46 UTC, tucksaun commented on commands/local_proxy_domain_attach.go
> +			return errors.WithStack(err)
this one should be wrapped in the parent function

2023-04-18 22:46 UTC, tucksaun commented on commands/local_proxy_domain_attach.go
> +			return errors.WithStack(err)
same

2023-04-18 22:46 UTC, tucksaun commented on commands/local_proxy_start.go
> +					return errors.WithStack(err)
IIRC `console.ExitCoder` errors must not be wrapped as we have special handling for them in `symfony-cli/console`

2023-04-20 13:44 UTC, darkweak commented
@tucksaun I'll open some PRs to review easier. I'll start with one that add only golangci-lint in the project with the given configuration without noises. The PR should be ready this evening. ✌️

2023-04-20 14:18 UTC, closed without merging